spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/oracle11
    username: aqadm
    password: aqadm

oracle:
  advanced:
    queue:
      name: AQ_QUEUE1
      table: AQ_TABLE1

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always